In [1]:
# SETUP yours
user_libs = "C:/Users/User/AppData/Local/R/cache/R/renv/library/functional-data-regression-mip-e3349204/R-4.3/x86_64-w64-mingw32"
.libPaths(c(user_libs,.libPaths()))



In [2]:


# run_simulation.R
# This script contains the function to run the simulation and returns all relevant outputs.

library(refund)
library(MASS)
library(fda)
library(here)

# Source the generic simulator script
source(here("src", "R", "generic_simulator", "simulate_main.R"))
source(here("src", "R", "generic_simulator", "utils","loader_utilities.R"))


# Define the function to run the simulation
run_simulation <- function(params) {
  # Ensure that the seed is set for reproducibility
  
  # Call the main analysis function with the parameters
  result <- do.call(generate_data, params[c("predictors", "observations", "measurements", "basis_functions", "intercept", "norder", "mu_funcs", "beta_funcs","time_domains", "cov_funcs", "seed","noise_snr","simulation_type")] )
    
  # Return the output list
  return(result)
}


simulation_name = "paper"
simulation_settings_file = "default"
# Required inputs before running the simulation!!!
inputs  <- load_simulation_settings(simulation_name, simulation_settings_file)
inputs$measurements <- 100
inputs$observations <- 400
inputs$basis_functions <- 6
time_domains_eval <- lapply(inputs$time_domains, function(domain) {
           seq(from = domain[[1]], to = domain[[2]], length.out = inputs$measurements)
       })
inputs$time_domains <- time_domains_eval
inputs$noise_snr <- c(FALSE,100)
outputs <- run_simulation(inputs);



Warning message:
"il pacchetto 'refund' è stato creato con R versione 4.3.2"
Warning message:
"il pacchetto 'fda' è stato creato con R versione 4.3.2"
Caricamento del pacchetto richiesto: splines

Caricamento del pacchetto richiesto: fds

Warning message:
"il pacchetto 'fds' è stato creato con R versione 4.3.2"
Caricamento del pacchetto richiesto: rainbow

Warning message:
"il pacchetto 'rainbow' è stato creato con R versione 4.3.2"
Caricamento del pacchetto richiesto: pcaPP

Warning message:
"il pacchetto 'pcaPP' è stato creato con R versione 4.3.2"
Caricamento del pacchetto richiesto: RCurl

Warning message:
"il pacchetto 'RCurl' è stato creato con R versione 4.3.2"
Caricamento del pacchetto richiesto: deSolve

Warning message:
"il pacchetto 'deSolve' è stato creato con R versione 4.3.2"

Caricamento pacchetto: 'fda'


Il seguente oggetto è mascherato da 'package:graphics':

    matplot


Warning message:
"il pacchetto 'here' è stato creato con R versione 4.3.2"
Warning message in re

[1] 100 NaN NaN
[1] "predictors: 6"
[1] "observations: 400"
[1] "measurements: 100"
[1] "basis_functions: 6"
[1] "intercept: 0"
[1] 540.59142  99.80446  29.34676  72.13334 113.10729 125.23074
[1] 10.51154


In [3]:
## ADAPTATION TO GETHEIS DATA
X = outputs$X
Y = outputs$Y
obseravation = dim(X)[1]    
predictors = dim(X)[2]
measurements = dim(X)[3]
basis_functions = inputs$basis_function


fobs <- list()
for (j in 1:predictors) {
  fobs[[j]] <- matrix(0, obseravation, measurements)
  for (i in 1:obseravation) {
    fobs[[j]][i,] <- X[i,j,]
  }
}

tps <- list()
# for any time_domain, create a vector of time points from 1:measurements
tps <- inputs$time_domains

In [4]:
obseravation = dim(X)[1]    
predictors = dim(X)[2]
measurements = dim(X)[3]

X_matrix <- array(data = X, dim = c(obseravation, predictors * measurements))
group <- rep(1:predictors, each = measurements) # This is an example where each measurement for a predictor is considered its own group

dim(X_matrix)

[1] 400 600

In [5]:
Y_vector <- as.numeric(Y)
index <- c( rep(1:predictors, each = measurements))


if(inputs$intercept > 0)
{
    index <- c(NA, rep(1:predictors, each = measurements))
    intercept_column <- rep(1, observations)
    X_matrix <- cbind(intercept_column, X_matrix)
}
index

[1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 [38] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 [75] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
[112] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[149] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[186] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
[223] 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
[260] 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
[297] 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
[334] 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
[371] 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5
[408] 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[445] 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[482] 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
[519] 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
[556] 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
[593] 6 6 6 6 6 6 6 6

In [6]:
require(splines)
require(grplasso)

grpl = grplasso(x = X_matrix, y = Y_vector, index = index, lambda = 200,model = LinReg (),center=FALSE)

Caricamento del pacchetto richiesto: grplasso

Warning message:
"il pacchetto 'grplasso' è stato creato con R versione 4.3.0"


Lambda: 200  nr.var: 500 


In [7]:
# Assuming your grplasso model is named 'grpl'

# Print the structure of the model object to understand what's available
print("Structure of the grplasso model object:")
str(grpl)

# Get and print the coefficients from the model
coefficients <- coef(grpl)
print("Coefficients from the grplasso model:")
print(coefficients)

# Identify and print non-zero coefficients to see which variables were selected
selected_variables <- which(coefficients != 0)
print("Indices of selected variables with non-zero coefficients:")
print(selected_variables)

# If the grplasso object contains fitted values, calculate and print R-squared
if ("fitted.values" %in% names(grpl)) {
  fitted_values <- grpl$fitted.values
  r_squared <- cor(Y, fitted_values)^2
  print("R-squared for the grplasso model:")
  print(r_squared)
}



[1] "Structure of the grplasso model object:"
List of 18
 $ x                : NULL
 $ y                : num [1:400] 8.67 8.3 5.18 6.29 6.77 ...
 $ coefficients     : num [1:600, 1] 0 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : NULL
  .. ..$ : chr "200"
 $ norms.pen        : num [1:6, 1] 0 0.394 0.686 0.854 1.556 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : NULL
  .. ..$ : chr "200"
 $ lambda           : num 200
 $ index            : int [1:600] 1 1 1 1 1 1 1 1 1 1 ...
 $ penscale         :function (x)  
 $ model            :Formal class 'grpl.model' [package "grplasso"] with 8 slots
  .. ..@ invlink  :function (eta)  
  .. ..@ link     :function (mu)  
  .. ..@ nloglik  :function (y, eta, weights, ...)  
  .. ..@ ngradient:function (x, y, mu, weights, ...)  
  .. ..@ nhessian :function (x, mu, weights, ...)  
  .. ..@ check    :function (y)  
  .. ..@ name     : chr "Linear Regression Model"
  .. ..@ comment  : chr "Use update.hess=\"lambda\" in grpl.co

In [8]:
compute_predictions_and_error <- function(coef_matrix, Z, Y_actual, true_predictors) {
  # Reshape coef_matrix to match the structure of Z
  reshaped_coefs <- as.vector(t(coef_matrix))
  
  # Compute predicted values
  Y_predicted <- Z %*% reshaped_coefs
  
  # Compute prediction error (MSE)
  mse <- mean((Y_actual - Y_predicted)^2)
  
  # Evaluate feature selection accuracy
  # Determine which predictors are selected by the model (non-zero coefficients)
  selected_predictors <- apply(coef_matrix, 1, function(row) any(row != 0))
  
  # Compare with true_predictors to calculate feature selection accuracy
  correct_selections <- sum(selected_predictors == true_predictors)
  total_predictors <- length(true_predictors)
  selection_accuracy <- correct_selections / total_predictors
  
  return(list(predicted = Y_predicted, mse = mse, accuracy = selection_accuracy))
}

to_matrix_form <-  function(predictor_coefficients, predictors, basis_functions) {
    # Create a matrix with 'basis_functions' elements per row
    # and the number of rows equal to the number of predictors from coeff_full
    coeff_matrix = matrix(0, nrow = predictors, ncol = basis_functions)

    for (i in 1:(predictors * basis_functions)) {
        # Calculate the row index as the ceiling of the division of 'i' by 'basis_functions'
        row_index = (i - 1) %/% basis_functions + 1
        # Calculate the column index as 'i' modulo 'basis_functions'; if modulo is 0, it means it's the last measurement
        col_index = ifelse(i %% basis_functions == 0, basis_functions, i %% basis_functions)
        # Assign the value of the coefficient to the matrix
        coeff_matrix[row_index, col_index] = predictor_coefficients[i]
}

  return(coeff_matrix)
}


true_predictors = inputs$true_predictors



In [9]:
Y[1:10]

[1] 8.665168 8.304177 5.179641 6.292358 6.766196 5.848521 8.244590 4.658787
 [9] 8.935064 8.441131

In [10]:
lambda = 10
grpl = grplasso(x = X_matrix, y = Y_vector, index = index, lambda = lambda,model = LinReg (),center=FALSE)

beta_star = to_matrix_form(grpl$coefficients, predictors, basis_functions)
beta_star

Lambda: 10  nr.var: 600 


[,1]         [,2]        [,3]          [,4]         [,5]        
[1,]  0.066648164 -0.07077923  0.0045796064 -0.061213492 -0.012901972
[2,]  0.067247946 -0.07517559 -0.0317359013 -0.029809659  0.005688417
[3,] -0.006802854  0.03672234  0.0005844911  0.030248022 -0.029879347
[4,]  0.061226130  0.13028596  0.0368252664 -0.095227915  0.045291591
[5,] -0.007486379 -0.01993437  0.0122667697 -0.028057665 -0.044647230
[6,] -0.034717132  0.03142991 -0.0316792289 -0.009408945  0.044137122
     [,6]       
[1,] -0.01772449
[2,] -0.01558323
[3,]  0.05281271
[4,] -0.02119965
[5,]  0.01315056
[6,] -0.05728876

In [11]:
beta_matrix = outputs$B
beta_matrix

[,1]         [,2]      [,3]      [,4]      [,5]      [,6]     
[1,] 5.012281e-06 0.1111006 0.3333244 0.6299252 0.7814756 0.8414660
[2,] 1.764154e-04 0.2323649 0.6976152 1.0681552 0.9830768 0.8659877
[3,] 0.000000e+00 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
[4,] 1.764154e-04 0.2323649 0.6976152 1.0681552 0.9830768 0.8659877
[5,] 0.000000e+00 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
[6,] 0.000000e+00 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000

In [12]:
max(beta_star)

[1] 0.130286

In [13]:
beta_funcs = inputs$beta_funcs
time_domains = inputs$time_domains
Betas <- create_beta_curves(beta_funcs, time_domains)


In [14]:
Betas

[,1] [,2]       [,3]       [,4]       [,5]       [,6]       [,7]      
[1,] 0    0.01010084 0.02020065 0.03029839 0.04039305 0.05048358 0.06056897
[2,] 0    0.02115393 0.04229839 0.06342392 0.08452107 0.10558039 0.12659245
[3,] 0    0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
[4,] 0    0.02115393 0.04229839 0.06342392 0.08452107 0.10558039 0.12659245
[5,] 0    0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
[6,] 0    0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
     [,8]       [,9]       [,10]      [,11] [,12]     [,13]     [,14]    
[1,] 0.07064817 0.08072016 0.09078392 ...   0.7889455 0.7951118 0.8011970
[2,] 0.14754787 0.16843725 0.18925124 ...   0.9450008 0.9378706 0.9303206
[3,] 0.00000000 0.00000000 0.00000000 ...   0.0000000 0.0000000 0.0000000
[4,] 0.14754787 0.16843725 0.18925124 ...   0.9450008 0.9378706 0.9303206
[5,] 0.00000000 0.00000000 0.00000000 ...   0.0000000 0.0000000 0.0000000
[6,] 0.00000000 0.00000000 0.00000000 ...   0.0000000 0.0000000 0.0000000
     [,15]     [,16]     [,17]     [,18]     [,19]     [,20]     [,21]    
[1,] 0.8072005 0.8131216 0.8189598 0.8247144 0.8303848 0.8359706 0.8414710
[2,] 0.9223543 0.9139752 0.9051870 0.8959938 0.8863995 0.8764086 0.8660254
[3,] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
[4,] 0.9223543 0.9139752 0.9051870 0.8959938 0.8863995 0.8764086 0.8660254
[5,] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
[6,] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000

In [15]:
outputs$beta_point_values

[,1] [,2]       [,3]       [,4]       [,5]       [,6]       [,7]      
[1,] 0    0.01010084 0.02020065 0.03029839 0.04039305 0.05048358 0.06056897
[2,] 0    0.02115393 0.04229839 0.06342392 0.08452107 0.10558039 0.12659245
[3,] 0    0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
[4,] 0    0.02115393 0.04229839 0.06342392 0.08452107 0.10558039 0.12659245
[5,] 0    0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
[6,] 0    0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
     [,8]       [,9]       [,10]      [,11] [,12]     [,13]     [,14]    
[1,] 0.07064817 0.08072016 0.09078392 ...   0.7889455 0.7951118 0.8011970
[2,] 0.14754787 0.16843725 0.18925124 ...   0.9450008 0.9378706 0.9303206
[3,] 0.00000000 0.00000000 0.00000000 ...   0.0000000 0.0000000 0.0000000
[4,] 0.14754787 0.16843725 0.18925124 ...   0.9450008 0.9378706 0.9303206
[5,] 0.00000000 0.00000000 0.00000000 ...   0.0000000 0.0000000 0.0000000
[6,] 0.00000000 0.00000000 0.00000000 ...   0.0000000 0.0000000 0.0000000
     [,15]     [,16]     [,17]     [,18]     [,19]     [,20]     [,21]    
[1,] 0.8072005 0.8131216 0.8189598 0.8247144 0.8303848 0.8359706 0.8414710
[2,] 0.9223543 0.9139752 0.9051870 0.8959938 0.8863995 0.8764086 0.8660254
[3,] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
[4,] 0.9223543 0.9139752 0.9051870 0.8959938 0.8863995 0.8764086 0.8660254
[5,] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
[6,] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000

In [17]:

 
 # Call the appropriate data generation function based on simulation type
  if (simulation_type == "paper") {
    data <- simulate_paper_data(mu_funcs, beta_funcs, observations, time_domains, intercept, predictors, noise_snr)
  } else{
    data <- simulate_cov_data(mu_funcs, cov_funcs, beta_funcs, observations, time_domains, intercept, predictors, noise_snr) 
  }

  # Extract U, X, Y from the returned data
  U <- data$U
  X <- data$X
  Y <- data$Y

  beta_point_values <- create_beta_curves(beta_funcs, time_domains)

  # Remaining processing steps
  basis_objs <- create_basis(basis_functions, time_domains, norder, predictors)
  result <- smooth_betas_generic(beta_point_values, basis_functions, time_domains, basis_objs)
  Beta_matrix <- result$beta_matrix
  basis_values <- result$basis_values
  beta_point_values <- result$beta_point_values
  J <- compute_J_matrix_generic(basis_objs, predictors, basis_functions)
  W <- compute_W_matrix_generic(X, basis_functions, time_domains, basis_objs)
  Z_matrix <- compute_Z_matrix_generic(W, J, predictors, basis_functions)

[1] 758.40096 117.02370  28.85060  65.90159 108.24558 100.78426
[1] 13.92606


In [18]:
err = 0 
for (K in 1:100){
    cumulative = 0 
for (i in 1:predictors) {
    cumulative = cumulative +t(W[K,i,]) %*% J[i,,] %*% Beta_matrix[i,]
}
# reconstruct Y[1] from W J and beta
cumulative2 = 0 
for (i in 1:predictors) {
    cumulative2 = cumulative + t(Z_matrix[K,i,]) %*% Beta_matrix[i,]
}



err = err + (Y[K] - cumulative2 )
}
# reconstruct Y[1] from W J and beta
print(err)

           [,1]
[1,] -0.5344167
